name: CI

on:
  push:
    tags: ["v*"]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  lint:
    name: PR Linting
    runs-on: ubuntu-latest
    steps:
      - name: Run Python quality checks
        uses: thekhoo/github-actions-shared/.github/actions/python-linting@main
        with:
          python-version: 3.13
          directories: datagovmy/ tests/
          use-ruff: true
          use-pyrefly: true

  test:
    name: PR Unit Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13", "3.14"]
    steps:
      - name: Run Python quality checks
        uses: thekhoo/github-actions-shared/.github/actions/python-pytest@main
        with:
          python-version: ${{ matrix.python-version }}
          test-directories: tests/
