name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  lint-and-test:
    name: CI
    uses: thekhoo/github-actions-shared/.github/workflows/python-ci.yml@main
    with:
      linting-python-version: "3.13"
      pytest-python-versions: '["3.11", "3.12", "3.13", "3.14"]'
      lint-directories: "pyrail_uk/ tests/"
      use-ruff: true
      use-pyrefly: true
      test-directories: "tests/"
